### ISSUE TITLE
Crash when changing theme in runtime 2 times

### ISSUE THREAD

**Issue by maicol07** [UN-GCPDS/pyside-material#2]
When changing theme in runtime 2 times the app crashes.

Error code:

```
Process finished with exit code -1073741819 (0xC0000005)
```

Steps:

Change theme to one of pyside-material 2 times, one after the other

**Comment by YeisonCardona** [comment]
Hi @maicol07, you are right, there was a bug on reload resources. I added to the example in [test/main.py](https://github.com/UN-GCPDS/pyside-material/blob/master/test/main.py) the feature to change the theme on runtime that seems to works for me, 
could you test it on your system, thanks.

**Comment by maicol07** [comment]
Ok, this is fixed
