### ISSUE TITLE
Pyinstaller Error

### ISSUE THREAD

**Issue by sihyeonlee** [UN-GCPDS/pyside-material#5]
Hello,
When I create my own script as an executable file using a pyinstaller, the following problems occur:
FileNotFoundError : ../pyside_material/fonts
The following errors also occur:
Warning: /pyside_material/themes/dark_cyan.xml not expist!
It works normally in the local environment, but this error occurs when I create an executable file and run it.
I don't think it properly routing the file, so please check it.
Thank you.

**Comment by YeisonCardona** [comment]
@sihyeonlee Are you including correctly the [data files with PyInstaller](https://pyinstaller.readthedocs.io/en/stable/spec-files.html)?

**Comment by sihyeonlee** [comment]
@YeisonCardona Yes, I including data files correctly.
And I solved this problem, the Python version problem.
There was a problem with version 3.7.9. In version 3.6.8, the problem was solved.
Maybe it was a problem on the Pyinstaller side.
Thanks.
